"""add total amount in purchases

Revision ID: 370e4e603f07
Revises: 2de6aa40ab22
Create Date: 2025-03-02 15:09:54.799570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370e4e603f07'
down_revision: Union[str, None] = '2de6aa40ab22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'total_amount')
    # ### end Alembic commands ###
