"""upgrade tables

Revision ID: 5120c8819e66
Revises: 1fd69c7beea0
Create Date: 2025-03-02 16:52:49.194092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5120c8819e66'
down_revision: Union[str, None] = '1fd69c7beea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_shares_id', table_name='item_shares')
    op.drop_column('item_shares', 'id')
    op.drop_index('ix_purchase_customers_id', table_name='purchase_customers')
    op.drop_column('purchase_customers', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_customers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_purchase_customers_id', 'purchase_customers', ['id'], unique=False)
    op.add_column('item_shares', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_item_shares_id', 'item_shares', ['id'], unique=False)
    # ### end Alembic commands ###
