"""add created_by for customers

Revision ID: b5fec35ab35c
Revises: 370e4e603f07
Create Date: 2025-03-02 15:54:12.339477

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b5fec35ab35c'
down_revision: Union[str, None] = '370e4e603f07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customers', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'created_by')
    # ### end Alembic commands ###
